name: deploy-mig

on:
  push:
    branches: [ main ]
    paths:
      - 'mig/**'

jobs:
  deploy:
    runs-on: [self-hosted]

    steps:
      - uses: actions/checkout@v4

      - name: sync files
        run: |
          rsync -av --delete mig/ /var/www/mig.labo.danmaid.com/html/
